/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'learner' : IDL.Null,
  'teacher' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'subject' : IDL.Text,
  'role' : UserRole,
  'profileInfo' : IDL.Text,
});
export const Group = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'learners' : IDL.Vec(IDL.Principal),
  'teacher' : IDL.Principal,
  'isActive' : IDL.Bool,
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'senderUsername' : IDL.Text,
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'subject' : IDL.Text,
  'scheduledTime' : IDL.Text,
  'googleMeetLink' : IDL.Text,
  'teacher' : IDL.Principal,
  'groupId' : IDL.Nat,
});
export const AikyaUser = IDL.Record({
  'username' : IDL.Text,
  'subject' : IDL.Text,
  'role' : UserRole,
  'profileInfo' : IDL.Text,
});
export const Note = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
export const Review = IDL.Record({
  'teacher' : IDL.Principal,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addNotification' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'clearNotifications' : IDL.Func([], [], []),
  'createSession' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getGroup' : IDL.Func([IDL.Nat], [Group], ['query']),
  'getGroupChatMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getMyGroup' : IDL.Func([], [IDL.Opt(Group)], ['query']),
  'getMyGroupSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getMyUser' : IDL.Func([], [IDL.Opt(AikyaUser)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTeacherReviews' : IDL.Func([IDL.Principal], [IDL.Vec(Review)], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(AikyaUser)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, UserRole, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendChatMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({ 'learner' : IDL.Null, 'teacher' : IDL.Null });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'subject' : IDL.Text,
    'role' : UserRole,
    'profileInfo' : IDL.Text,
  });
  const Group = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'learners' : IDL.Vec(IDL.Principal),
    'teacher' : IDL.Principal,
    'isActive' : IDL.Bool,
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'senderUsername' : IDL.Text,
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'subject' : IDL.Text,
    'scheduledTime' : IDL.Text,
    'googleMeetLink' : IDL.Text,
    'teacher' : IDL.Principal,
    'groupId' : IDL.Nat,
  });
  const AikyaUser = IDL.Record({
    'username' : IDL.Text,
    'subject' : IDL.Text,
    'role' : UserRole,
    'profileInfo' : IDL.Text,
  });
  const Note = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const Review = IDL.Record({
    'teacher' : IDL.Principal,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addNotification' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'clearNotifications' : IDL.Func([], [], []),
    'createSession' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getGroup' : IDL.Func([IDL.Nat], [Group], ['query']),
    'getGroupChatMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getMyGroup' : IDL.Func([], [IDL.Opt(Group)], ['query']),
    'getMyGroupSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getMyUser' : IDL.Func([], [IDL.Opt(AikyaUser)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTeacherReviews' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(AikyaUser)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, UserRole, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendChatMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };