/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AikyaUser {
  'username' : string,
  'subject' : string,
  'role' : UserRole,
  'profileInfo' : string,
}
export interface ChatMessage {
  'senderUsername' : string,
  'sender' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export interface Group {
  'id' : bigint,
  'subject' : string,
  'learners' : Array<Principal>,
  'teacher' : Principal,
  'isActive' : boolean,
}
export interface Note { 'title' : string, 'content' : string }
export interface Review {
  'teacher' : Principal,
  'comment' : string,
  'rating' : bigint,
  'reviewer' : Principal,
}
export interface Session {
  'id' : bigint,
  'topic' : string,
  'subject' : string,
  'scheduledTime' : string,
  'googleMeetLink' : string,
  'teacher' : Principal,
  'groupId' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'subject' : string,
  'role' : UserRole,
  'profileInfo' : string,
}
export type UserRole = { 'learner' : null } |
  { 'teacher' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNote' : ActorMethod<[string, string], undefined>,
  'addNotification' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[Principal, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'clearNotifications' : ActorMethod<[], undefined>,
  'createSession' : ActorMethod<[bigint, string, string, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getGroup' : ActorMethod<[bigint], Group>,
  'getGroupChatMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getMyGroup' : ActorMethod<[], [] | [Group]>,
  'getMyGroupSessions' : ActorMethod<[], Array<Session>>,
  'getMyUser' : ActorMethod<[], [] | [AikyaUser]>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getNotifications' : ActorMethod<[], Array<string>>,
  'getTeacherReviews' : ActorMethod<[Principal], Array<Review>>,
  'getUser' : ActorMethod<[Principal], [] | [AikyaUser]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, string, UserRole, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendChatMessage' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];